import {
  FiGrid,
  FiPackage,
  FiLayers,
  FiBox,
  FiTag,
  FiTruck,
  FiShoppingCart,
  FiClock,
  FiRotateCcw,
  FiFileText,
  FiClipboard,
  FiDownload,
  FiUsers,
  FiSearch,
  FiHeart,
  FiUserCheck,
  FiShield,
  FiCalendar,
  FiBarChart2,
  FiTrendingUp,
  FiAlertTriangle,
  FiBell,
  FiMail,
  FiCloud,
  FiRefreshCw,
  FiList,
  FiSettings,
  FiDollarSign,
  FiGlobe,
  FiLock,
  FiKey,
  FiActivity,
  FiPieChart,
} from 'react-icons/fi';
import { TbPill } from 'react-icons/tb';

export const navigation = [
  {
    label: 'Dashboard',
    icon: FiGrid,
    to: '/dashboard',
  },
  {
    label: 'Inventory',
    icon: FiPackage,
    children: [
      { label: 'Medicine Management', to: '/medicines', icon: TbPill },
      { label: 'Stock Management', to: '/inventory/stock', icon: FiLayers },
      { label: 'Categories', to: '/inventory/categories', icon: FiTag },
      { label: 'Batches', to: '/inventory/batches', icon: FiBox },
      { label: 'Manufacturers', to: '/inventory/manufacturers', icon: FiActivity },
      { label: 'Suppliers', to: '/inventory/suppliers', icon: FiTruck },
    ],
  },
  {
    label: 'Sales',
    icon: FiShoppingCart,
    children: [
      { label: 'POS Billing', to: '/sales/pos', icon: FiShoppingCart },
      { label: 'Sales History', to: '/sales/history', icon: FiClock },
      { label: 'Returns & Refunds', to: '/sales/returns', icon: FiRotateCcw },
      { label: 'Quotations', to: '/sales/quotations', icon: FiFileText },
    ],
  },
  {
    label: 'Purchase',
    icon: FiClipboard,
    children: [
      { label: 'Purchase Orders', to: '/purchase/orders', icon: FiClipboard },
      { label: 'Receive Stock', to: '/purchase/receive', icon: FiDownload },
      { label: 'Purchase History', to: '/purchase/history', icon: FiClock },
    ],
  },
  {
    label: 'Customers',
    icon: FiUsers,
    children: [
      { label: 'Customer List', to: '/customers', icon: FiUsers },
      { label: 'Medicine Availability', to: '/customers/availability', icon: FiSearch },
      { label: 'Prescriptions', to: '/customers/prescriptions', icon: FiFileText },
      { label: 'Loyalty Program', to: '/customers/loyalty', icon: FiHeart },
    ],
  },
  {
    label: 'Employees',
    icon: FiUserCheck,
    children: [
      { label: 'Staff', to: '/employees/staff', icon: FiUsers },
      { label: 'Roles & Permissions', to: '/employees/roles', icon: FiShield },
      { label: 'Attendance', to: '/employees/attendance', icon: FiCalendar },
    ],
  },
  {
    label: 'Reports',
    icon: FiBarChart2,
    children: [
      { label: 'Sales Report', to: '/reports/sales', icon: FiBarChart2 },
      { label: 'Inventory Report', to: '/reports/inventory', icon: FiPackage },
      { label: 'Profit Analysis', to: '/reports/profit', icon: FiTrendingUp },
      { label: 'Expiry Report', to: '/reports/expiry', icon: FiAlertTriangle },
      { label: 'Purchase Report', to: '/reports/purchase', icon: FiClipboard },
      { label: 'Tax Report', to: '/reports/tax', icon: FiFileText },
    ],
  },
  {
    label: 'Analytics',
    icon: FiPieChart,
    children: [
      { label: 'Dashboard Analytics', to: '/analytics/dashboard', icon: FiGrid },
      { label: 'Demand Forecast', to: '/analytics/forecast', icon: FiTrendingUp },
      { label: 'Best Selling Medicines', to: '/analytics/best-selling', icon: TbPill },
    ],
  },
  {
    label: 'Notifications',
    icon: FiBell,
    children: [
      { label: 'Low Stock Alerts', to: '/notifications/low-stock', icon: FiAlertTriangle },
      { label: 'Expiry Alerts', to: '/notifications/expiry', icon: FiClock },
      { label: 'Orders', to: '/notifications/orders', icon: FiBell },
      { label: 'Messages', to: '/notifications/messages', icon: FiMail },
    ],
  },
  {
    label: 'Cloud',
    icon: FiCloud,
    children: [
      { label: 'Backup & Restore', to: '/cloud/backup', icon: FiCloud },
      { label: 'Sync Status', to: '/cloud/sync', icon: FiRefreshCw },
      { label: 'Audit Logs', to: '/cloud/audit', icon: FiList },
    ],
  },
  {
    label: 'Settings',
    icon: FiSettings,
    children: [
      { label: 'Pharmacy Profile', to: '/settings/profile', icon: FiSettings },
      { label: 'Taxes', to: '/settings/taxes', icon: FiFileText },
      { label: 'Currency', to: '/settings/currency', icon: FiGlobe },
      { label: 'User Management', to: '/settings/users', icon: FiUsers },
      { label: 'Security', to: '/settings/security', icon: FiLock },
      { label: 'API Keys', to: '/settings/api-keys', icon: FiKey },
    ],
  },
];
